In [3]:
import numpy as np
import math

In [2]:
c = np.array([45,3,8,2,7,24])
lp = [4,2,5,25]

In [4]:
z = 7
math.sqrt(z)

2.6457513110645907

In [7]:
# math.sqrt(lp)

for wr in lp:
    print(math.sqrt(wr))

2.0
1.4142135623730951
2.23606797749979
5.0


In [8]:
np.sqrt(c)

array([6.70820393, 1.73205081, 2.82842712, 1.41421356, 2.64575131,
 4.89897949])

In [9]:
np.sqrt(lp)

array([2. , 1.41421356, 2.23606798, 5. ])

In [10]:
np.sinc(c)

array([ 1.38514097e-17, 3.89817183e-17, -3.89817183e-17, -3.89817183e-17,
 3.89817183e-17, -3.89817183e-17])

In [ ]:
#utwórz macierz w wymiarze (3,5) poprzez wygenerowanie wartości dla tej macierzy

In [11]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [13]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [14]:
arr =np.random.randn(6,3)
arr

array([[-0.20968362, 2.18515198, 0.10445535],
 [ 0.42033165, -1.43026473, 1.00122306],
 [ 1.22637595, 0.17831999, -0.5514244 ],
 [ 0.16165188, -1.00357622, 0.20475206],
 [ 0.93031962, -0.03716505, -0.46487211],
 [-0.23877084, -0.63956172, -0.58386358]])

In [15]:
arr.T

array([[-0.20968362, 0.42033165, 1.22637595, 0.16165188, 0.93031962,
 -0.23877084],
 [ 2.18515198, -1.43026473, 0.17831999, -1.00357622, -0.03716505,
 -0.63956172],
 [ 0.10445535, 1.00122306, -0.5514244 , 0.20475206, -0.46487211,
 -0.58386358]])

In [16]:
np.dot(arr.T,arr)

array([[ 2.67328134, -0.88478543, -0.53728196],
 [-0.88478543, 8.26993006, -1.11688371],
 [-0.53728196, -1.11688371, 1.91635356]])

In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

result = np.dot(a,b)
result

array([17, 39])

wynik iloczyny skalarnego a x b
[1*5+2*6,3*5+4*6] = [17,39]

In [19]:
#jak zbudowac tensor?
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [21]:
arlos = np.random.rand(3,6,3)
arlos

array([[[6.70806031e-01, 9.34239432e-01, 6.76226311e-01],
        [5.16076651e-01, 8.87670058e-01, 7.48597511e-01],
        [4.16164458e-01, 6.33562730e-01, 2.59911270e-01],
        [7.38662141e-01, 9.27826982e-01, 9.65982798e-01],
        [9.01238564e-01, 1.41373052e-01, 8.76496800e-01],
        [4.51557717e-01, 8.12850427e-01, 6.38578774e-01]],

       [[6.71256998e-01, 4.19632969e-01, 2.87537169e-01],
        [2.70929999e-01, 5.36353847e-01, 8.32465965e-01],
        [4.36768305e-01, 9.73835067e-02, 9.67128326e-01],
        [1.34927257e-01, 1.93057238e-01, 7.66441119e-01],
        [5.76423705e-02, 4.56531256e-01, 2.76733128e-02],
        [1.13785334e-01, 7.73130169e-01, 4.60959383e-01]],

       [[8.40535304e-01, 9.36067789e-01, 4.51010305e-02],
        [9.33162688e-01, 3.06878173e-01, 5.31186245e-04],
        [5.05842434e-01, 9.15770883e-01, 2.86567128e-02],
        [1.49305065e-01, 1.75296714e-01, 9.79519287e-02],
        [9.54792974e-02, 2.98561637e-01, 4.42982662e-01],
        [3

In [23]:
#zbuduj dwa tensory o kształcie kostki Rubika (3x3x3) -  losując dane 
#wykonaj mnożenie tych tensorów i wyświetl wynik

# Tworzenie dwóch losowych tensorów o kształcie (3, 3, 3)
tensor1 = np.random.rand(3, 3, 3)
tensor2 = np.random.rand(3, 3, 3)

# Mnożenie tensorów
result = np.einsum('ijk,ikl->ijl', tensor1, tensor2)

# Wyświetlenie tensorów i wyniku
print("Tensor 1:")
print(tensor1)

print("\nTensor 2:")
print(tensor2)

print("\nWynik mnożenia tensorów:")
print(result)

Tensor 1:
[[[0.47466277 0.36383956 0.27325712]
  [0.33225486 0.7356162  0.74521896]
  [0.20499317 0.69786811 0.6633395 ]]

 [[0.16277652 0.43258595 0.48918885]
  [0.2111215  0.8623825  0.18548738]
  [0.93597162 0.46167747 0.31156733]]

 [[0.2893515  0.08388582 0.60385675]
  [0.67191073 0.38684501 0.84011449]
  [0.94410906 0.20760885 0.00581043]]]

Tensor 2:
[[[0.14842641 0.67183088 0.86341559]
  [0.0040577  0.02870166 0.76364849]
  [0.72565544 0.7096696  0.98335603]]

 [[0.75258088 0.65204348 0.74997058]
  [0.14582382 0.31492115 0.07295196]
  [0.25507796 0.29239057 0.79526968]]

 [[0.87328657 0.85819057 0.83976043]
  [0.95361751 0.307219   0.78621938]
  [0.87416164 0.30514344 0.37120998]]]

Wynik mnożenia tensorów:
[[[0.27021936 0.52325818 0.95638581]
  [0.59307249 0.77319171 1.58144178]
  [0.51461405 0.62850259 1.36221912]]

 [[0.31036512 0.38540204 0.54267265]
  [0.33195566 0.46347765 0.3687599 ]
  [0.85119188 0.84678555 0.98341151]]

 [[0.86055017 0.45835297 0.53309625]
  [1.6900686

In [24]:
tensor1 = np.random.rand(3, 3, 3)
tensor2 = np.random.rand(3, 3, 3)

t = tensor1*tensor2

t

array([[[1.54711346e-01, 7.92464188e-01, 2.60322861e-02],
        [5.76800741e-01, 5.29815254e-02, 2.49109104e-02],
        [2.92804065e-01, 1.36058753e-01, 5.97759243e-02]],

       [[9.09693384e-02, 1.77840276e-01, 2.17256707e-01],
        [3.11358853e-02, 1.39665756e-01, 8.26042630e-02],
        [5.82813118e-02, 1.62091903e-01, 5.64976606e-01]],

       [[5.79445527e-01, 1.64963113e-01, 3.84781458e-01],
        [2.39317990e-01, 3.40099482e-04, 1.59869947e-01],
        [4.77852107e-01, 5.49881199e-01, 1.28262286e-01]]])