In [1]:
print("to jest pierwsza komórka!")
d = 45

to jest pierwsza komórka!


In [2]:
print(d)

45


To jest pierwszy **notebook** w temacie: <span style="color:red; font-size:16pt;">biblioteka numpy</span>

In [3]:
import datetime
dpwyjazd = (datetime.date(2024, 11, 08), datetime.date(2024, 11, 10))

In [4]:
print(dpwyjazd)

(datetime.date(2024, 11, 8), datetime.date(2024, 11, 10))


In [5]:
import numpy as np

In [6]:
np.zeros(14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(90,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1])

In [8]:
np.arange(1,200,4)

array([ 1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49,
 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101,
 105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
 157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197])

In [9]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [10]:
zlista = [5,3,7,3,8,57,9,46,9,35,2]
print(zlista)
print(type(zlista))

[5, 3, 7, 3, 8, 57, 9, 46, 9, 35, 2]
<class 'list'>


In [11]:
npz = np.array(zlista)
print(npz)
print(type(npz))

[ 5  3  7  3  8 57  9 46  9 35  2]
<class 'numpy.ndarray'>


In [12]:
kt = (0.3,3.4,64,True,8,9,10.3)
npkt = np.array(kt)
print(npkt)
print(type(npkt))

[ 0.3  3.4 64.   1.   8.   9.  10.3]
<class 'numpy.ndarray'>


In [13]:
npkt.sort()
npkt

array([ 0.3, 1. , 3.4, 8. , 9. , 10.3, 64. ])

In [14]:
zb = {5,2,6,8,5.5,13,85,4,2,2,2,67,8.9,12.3}
print(zb)

{2, 67, 4, 5.5, 5, 6, 8, 8.9, 12.3, 13, 85}


In [15]:
npzb = np.array(zb)
print(npzb)
print(type(npzb))

{2, 67, 4, 5.5, 5, 6, 8, 8.9, 12.3, 13, 85}
<class 'numpy.ndarray'>


In [17]:
# npzb.sort()
# npzb

In [ ]:
l1 = [5,3,7,2]
l2 = [8,24,6,25]
l3 = [134,245,6]